version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v4.1.x"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v4.0.x"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v3.13.x"
  # Maintain dependencies for Java test projects
  - package-ecosystem: "maven"
    directories:
      - "/deps/rabbit/test/amqp_jms_SUITE_data"
      - "/deps/rabbitmq_mqtt/test/java_SUITE_data"
      - "/deps/rabbitmq_stream/test/rabbit_stream_SUITE_data"
      - "/deps/rabbitmq_stream_management/test/http_SUITE_data"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    commit-message:
      prefix: "[skip ci] "
    target-branch: "main"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
  - package-ecosystem: "maven"
    directories:
      - "/deps/rabbit/test/amqp_jms_SUITE_data"
      - "/deps/rabbitmq_mqtt/test/java_SUITE_data"
      - "/deps/rabbitmq_stream/test/rabbit_stream_SUITE_data"
      - "/deps/rabbitmq_stream_management/test/http_SUITE_data"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    commit-message:
      prefix: "[skip ci] "
    target-branch: "v4.1.x"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
  - package-ecosystem: "maven"
    directories:
      - "/deps/rabbit/test/amqp_system_SUITE_data/java-tests"
      - "/deps/rabbitmq_mqtt/test/java_SUITE_data"
      - "/deps/rabbitmq_stream/test/rabbit_stream_SUITE_data"
      - "/deps/rabbitmq_stream_management/test/http_SUITE_data"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    commit-message:
      prefix: "[skip ci] "
    target-branch: "v4.0.x"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
  - package-ecosystem: "maven"
    directories:
      - "/deps/rabbitmq_management/selenium/amqp10-roundtriptest"
      - "/deps/rabbitmq_mqtt/test/java_SUITE_data"
      - "/deps/rabbitmq_stream/test/rabbit_stream_SUITE_data"
      - "/deps/rabbitmq_stream_management/test/http_SUITE_data"
      - "/deps/rabbitmq_amqp1_0/test/system_SUITE_data/java-tests"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot"
      - "/deps/rabbitmq_auth_backend_http/examples/rabbitmq_auth_backend_spring_boot_kotlin"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    commit-message:
      prefix: "[skip ci] "
    target-branch: "v3.13.x"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
